version: '3.7'

services:
  app:
    build: .
    image: ubunfu/db-app:latest
    ports:
      - "8080:8080"
    depends_on:
      - "database"
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db-app_database_1/db-app"
      SPRING_DATASOURCE_USERNAME: "user"
      SPRING_DATASOURCE_PASSWORD: "password"
  database:
    build: ./docker/mysql
    image: db-app-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "db-app"
